# Generated by Django 3.2.10 on 2022-01-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0041_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
